name = "mmmf"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "MMMF_KV"
id = "9e7bfc690528464f991e4ec210b54094" # Replace with your KV Namespace ID
